### ISSUE TITLE
Gird throws exception when sorting decimal column

### ISSUE THREAD

**Issue by kx197** [datalnet/DnetBlazor#1]
This issue should be reproducible if sorting is enabled on the Grid sample's Balance column: https://datalnet.com/BlGrid

![image](https://user-images.githubusercontent.com/11903892/210360157-ccc6b9b1-32ac-428c-9464-416d79773224.png)

I would very much appreciate a solution, as this grid is the fastest Blazor WASM grid I have found. Great job.

**Comment by datalnet** [comment]
Thank you very much let me look at it.

**Comment by adrian-mustelier** [comment]
@kx197 Is fixed now, I will try to publish a new release tomorrow. To solve the issue you should add to the grid column definition this to lines

 CellDataType = CellDataType.Number,
 IsDecimalCellDataType = true,

It might be more elegant to create a new CellDataType, but I use the DataType number in many places and it would take more time to solve the bug. In future releases I will try to add a new CellDataType of type Decimal. As it is solved, adding the CellDataType Decimal, will not mean a breaking change.

You can see the solution here
https://github.com/datalnet/DnetBlazor/blob/770b85161dadf1e351eb44ca8e83652d1fe21ddd/src/Dnet.Blazor/Components/Grid/Infrastructure/Services/Sorting.cs#L52

**Comment by datalnet** [comment]
Already publish version 2.1.1
