### ISSUE TITLE
Datepicker is not catching the date if you type directly.

### ISSUE THREAD

**Issue by RiveraIsmael** [datalnet/DnetBlazor#5]

**Comment by datalnet** [comment]
Done, Now also you can provide diffrenet formats to de component as shown in the followed code

`<DnetFormField Label="Departure day" UseClearButton="true" IsRequired="true">
                        <ChildContent>
                            <DnetDatePicker @bind-Value="@_formData.DepartureDay"
                                OnDaySelected="DaySelected" PlaceHolder="Departure day"
                                Format="@_datepickerFormat" MaxDayValue="DateTime.Now"
                                Formats="@(new string[] {"yyyy/MM/dd","yyyy/M/d","dd/MM/yyyy","d/M/yyyy"})"
                                >
                            </DnetDatePicker>
                        </ChildContent>
                        <SufixContent>
                            <div class="dnet-datepicker-icon-wrapper">
                                <span class="dnet-datepicker-icon dnet-datepicker-icon-default"
                                    unselectable="on"></span>
                            </div>
                        </SufixContent>
                        <ErrorContent>
                            <ValidationMessage For="@(() => _formData.DepartureDay)" />
                        </ErrorContent>
                    </DnetFormField>`
